server {
    listen 80;
    server_name localhost;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /api/products {
        if ($request_method = GET) { proxy_pass http://get-products:3001; }
        if ($request_method = POST) { proxy_pass http://create-product:3002; }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location ~ ^/api/products/(\d+)$ {
        if ($request_method = PUT) { proxy_pass http://update-product:3003; }
        if ($request_method = DELETE) { proxy_pass http://delete-product:3004; }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# 2026 - Disenador asignatura: Ignacio A. Pastenet M.
