name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Escribe DESTROY para confirmar la eliminación de TODA la infraestructura'
        required: true
        default: ""

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    defaults:
      run:
        working-directory: Prueba1/freshbox-ep1/infra/envs/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (secrets)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="db_pass=${{ secrets.DB_PASS }}" \
            -var="db_root_pass=${{ secrets.DB_ROOT_PASS }}" \
            -var="enable_backup=false"

      - name: Confirm environment deletion
        if: always()
        run: echo "Destroy finalizado. Los recursos de la infraestructura fueron eliminados."